$(document).ready(function(){$(".cblue").click(function(){$("link#clink").attr("href","css/style-blue.css");return false});$(".cred").click(function(){$("link#clink").attr("href","css/style-red.css");return false});$(".cgreen").click(function(){$("link#clink").attr("href","css/style-green.css");return false});$(".cmagenta").click(function(){$("link#clink").attr("href","css/style-magenta.css");return false});$(".cpurple").click(function(){$("link#clink").attr("href","css/style-purple.css");return false});
$(".cteal").click(function(){$("link#clink").attr("href","css/style-teal.css");return false});$(".clime").click(function(){$("link#clink").attr("href","css/style-lime.css");return false});$(".cbrown").click(function(){$("link#clink").attr("href","css/style-brown.css");return false});$(".cpink").click(function(){$("link#clink").attr("href","css/style-pink.css");return false});$(".cmango").click(function(){$("link#clink").attr("href","css/style-mango.css");return false});$("ul#nav li").hoverIntent(function(){$(this).children("ul").slideDown(300)},
function(){$(this).children("ul").slideUp(300)});$("<select />").appendTo("nav");$("<option />",{"selected":"selected","value":"","text":"Go to..."}).appendTo("nav select");$("nav a").each(function(){var el=$(this);$("<option />",{"value":el.attr("href"),"text":el.text()}).appendTo("nav select")});$("nav select").change(function(){window.location=$(this).find("option:selected").val()});function matrix_tiles_init(){$(".flexslider").flexslider();function matrix_fix_masonry(){var screenWidth=jQuery(window).width();
if(screenWidth<960)jQuery("#mainpage-mos").width(screenWidth);else jQuery("#mainpage-mos").width(960)}matrix_fix_masonry();jQuery(window).resize(matrix_fix_masonry);$("#content-mos").masonry({itemSelector:".tile",columnWidth:160,isAnimated:true,isFitWidth:true});$(".tile").not(".exclude").hover(function(){$(".tile").not(this).addClass("fade")},function(){$(".tile").removeClass("fade")});$(".live").liveTile({pauseOnHover:true});$("a.lightbox").click(function(){$(this).next(".tile-pre").addClass("tempsrc")});
var lbSRC="";$("a.lightbox").fancybox({"margin":0,"overlayColor":"#000","transitionIn":"elastic","transitionOut":"elastic","speedOut":100,"cyclic":true,"onComplete":function(){lbSRC=$("#fancybox-content").find("iframe").attr("src")},"onClosed":function(){$(".tempsrc").find("iframe").attr("src",lbSRC);$(".tile-pre").removeClass("tempsrc")}});matrix_media_player()}matrix_tiles_init();function show_twitter_on_tile(){var user="envato";var tweetcount=4;$.getJSON("https://api.twitter.com/1/statuses/user_timeline.json?screen_name="+
user+"&count="+tweetcount+"&callback=?",function(data){var tweet="";for(i=0;i<data.length;i++)tweet+="<li>"+data[i].text+"</li>";tweet=tweet.replace(/(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig,function(url){return'<a target="_blank" href="'+url+'">'+url+"</a>"}).replace(/B@([_a-z0-9]+)/ig,function(reply){return reply.charAt(0)+'<a href="http://twitter.com/'+reply.substring(1)+'">'+reply.substring(1)+"</a>"});$("#tweeter").html(tweet)})}show_twitter_on_tile();$(".toggle-button").click(function(){$(this).next("div.toggle-content").slideToggle("slow");
$(this).children(".toggle-indicator").text($(this).children(".toggle-indicator").text()=="+"?"-":"+")});$(".accordion .ac-tab").click(function(){$(this).next("div.toggle-content").slideToggle("slow").siblings("div.toggle-content").slideUp("slow");$(this).children(".toggle-indicator").text("-");$(this).siblings().children(".toggle-indicator").text("+")});$(".table-info ul li").hoverIntent(function(){$(this).next("div.table-details").slideDown("slow").siblings("div.table-details").slideUp("slow");$(this).children(".toggle-indicator").text("-");
$(this).siblings().children(".toggle-indicator").text("+")},function(){});$(".table-info ul").mouseleave(function(){$(this).children("div.table-details").slideUp("slow");$(this).find(".toggle-indicator").text("+")});var pathname=window.location.protocol+"//"+window.location.host+"/"+window.location.pathname;$.getJSON("http://graph.facebook.com/?id="+pathname+"",function(data){if(data.shares==undefined)$(".meta2 .count").prepend("0");else $(".meta2 .count").prepend(data.shares)});$.getJSON("http://urls.api.twitter.com/1/urls/count.json?url="+
pathname+"&callback=?",function(data){$(".meta3 .count").prepend(data.count)});$(".bloglist").hover(function(){$(this).css({"margin-top":"-5px"})},function(){$(this).css({"margin-top":"0"})});$("ul#port-filter a").click(function(){$(this).css("outline","none");$("ul#port-filter .filter-current").removeClass("filter-current");$(this).parent().addClass("filter-current");var filterVal=$(this).text().toLowerCase().replace(" ","-");if(filterVal=="all")$("div.hidden").fadeIn("fast").removeClass("hidden");
else{$("div#portfolio div.tile").each(function(){if(!$(this).hasClass(filterVal))$(this).fadeOut("fast").addClass("hidden");else $(this).fadeIn("fast").removeClass("hidden")});$("div.portfoliolist").each(function(){if(!$(this).hasClass(filterVal))$(this).fadeOut("fast").addClass("hidden");else $(this).fadeIn("fast").removeClass("hidden")})}return false});$("#demo-button").organicTabs();$("#demo-tab").organicTabs();$("[placeholder]").focus(function(){var input=$(this);if(input.val()==input.attr("placeholder")){input.val("");
input.removeClass("placeholder")}}).blur(function(){var input=$(this);if(input.val()==""||input.val()==input.attr("placeholder")){input.addClass("placeholder");input.val(input.attr("placeholder"))}}).blur().parents("form").submit(function(){$(this).find("[placeholder]").each(function(){var input=$(this);if(input.val()==input.attr("placeholder"))input.val("")})});jQuery(".ajax-pagination a").live("click",function(e){e.preventDefault();var link=jQuery(this).attr("href");jQuery("#loader").fadeIn(300);
jQuery.ajax({url:link,dataType:"html",context:document.body,cache:"false",beforeSend:function(){jQuery("#mainpage-mos").fadeOut(500)},success:function(html){var newhtml=jQuery("#mainpage-mos",jQuery(html));jQuery("script",newhtml).each(function(){jQuery.globalEval(jQuery(this).text())});show_twitter_on_tile();jQuery("#mainpage-mos").html(newhtml);jQuery("#mainpage-mos").fadeIn(500);matrix_tiles_init();var screenheight=jQuery(window).height();jQuery("#container").css("min-height",screenheight);jQuery("iframe").parent(".lb-video").removeAttr("style");
jQuery("#loader").fadeOut(300)},error:function(){alert("Error")}})});jQuery("a.jp-full-screen").click(function(){jQuery("a#fancybox-left, a#fancybox-close, a#fancybox-right").hide()});jQuery("a.jp-restore-screen").click(function(){jQuery("a#fancybox-left, a#fancybox-close, a#fancybox-right").show()});var vpWidth=jQuery(window).width();if(vpWidth<590){jQuery("article .jp-controls-holder").css("width",vpWidth-20+"px");var newWidth=vpWidth-280;jQuery("article .jp-progress").css("width",newWidth+"px")}jQuery("a.lightbox").click(function(){var vpWidth=
jQuery(window).width();if(vpWidth<590){jQuery("article .jp-controls-holder").css("width",vpWidth-20+"px");var newWidth=vpWidth-280;jQuery("article .jp-progress").css("width",newWidth+"px")}else{jQuery("article .jp-controls-holder").css("width",570+"px");jQuery("article .jp-progress").css("width",310+"px")}});jQuery(window).resize(function(){var vpWidth=jQuery("article .lb-audio").width();if(vpWidth<570){jQuery("article .jp-controls-holder").css("width",vpWidth+"px");var newWidth=vpWidth-260;jQuery("article .jp-progress").css("width",
newWidth+"px")}else{jQuery("article .jp-controls-holder").css("width",570+"px");jQuery("article .jp-progress").css("width",310+"px")}});var screenheight=$(window).height();$("#container").css("min-height",screenheight)});
